server:
  port: 8050

spring:
  application:
    name: product-catalog-svc
  r2dbc:
    url: ${JDBC_URL}
    username: ${username}
    password: ${password}
    pool:
      enabled: true
      initial-size: 5
      max-size: 20
  sql:
    init:
      mode: never

management:
  endpoints:
    web:
      exposure:
        # Expose only what's necessary to reduce attack surface
        include: health, info, prometheus, metrics 
  endpoint:
    health:
      # Required for /actuator/health/liveness and /actuator/health/readiness
      probes:
        enabled: true
      # Shows details (like DB status) to help you debug why it's DOWN
      show-details: always 
      group:
        readiness:
          # Include readiness state + your actual dependencies
          include: readinessState
        liveness:
          # Keep liveness minimal so transient DB blips don't restart the pod
          include: livenessState
  server:
    port: 8051
springdoc:
  swagger-ui:
    enabled: true
aws:
  dynamodb:
    region: ap-south-1
logging:
  level:
    root: INFO
